### ISSUE TITLE
Pointer to new repository?

### ISSUE THREAD

**Issue by david135** [akeep/nanopass-framework#18]
I might suggest a pointer to the new repository, the way there is for the [Racket Nanopass Compiler Library](https://github.com/akeep/nanopass-framework-racket)?

**Comment by akeep** [comment]
Yes, you're right I've been meaning to do that.

The Scheme (Chez/Ikarus/Vicare) repo is now at:

https://github.com/nanopass/nanopass-framework-scheme

The Racket repo is now at:
https://github.com/nanopass/nanopass-framework-racket

Lief Andersen is the main maintainer for the Racket version now and is using it for research.

I've got a short list of improvements and clean-up I need to make and I'll add this to it.

-andy:)
On April 28, 2016 at 12:38:52 PM, David Roth (notifications@github.com) wrote:

I might suggest a pointer to the new repository, the way there is for the Racket Nanopass Compiler Library?

**Comment by akeep** [comment]
Thanks again for the note.  Something I should have cleaned up a while ago.  I think Leif and I should have been a bit more coordinated on moving projects over to the nanopass group, I suspect I could have change ownership.  Of course this is mostly my fault, since I've been inconsistent about responding to email and keeping up with all of this.
